goals = ["divya","heena","cabin_joey","office_mary","racheal","left_cupboard","office_pc"]
#goals = ["robita_lab_entrance","waiting_area","robita_entrance_gate","office_gcn","cabin_joey",
#        "cabin_ross","classroom_entrance","light_switches",]
prob = {"office_gcn" : 0.5,
        "office_rk" : 0.5,
        "cabin_joey" : 0.5,
        "office_pc" : 0.5,
        "robita_entrance_gate" : 0.5,
        "office_mary" : 0.5,
        "waiting_area" : 0.5,
        "copying_station" : 0.5,
        "cabin_ross" : 0.5,
        "classroom_entrance" : 0.5,
        "robita_lab_entrance" : 0.5,
        "light_switches" : 0.5,
        "classroom_system" :0.5,
        "whiteboard" : 0.5,
        "wall_ac_front" : 0.5,
        "wall_ac_back" : 0.5,
        "back_right_ac" : 0.5,
        "back_left_ac" :0.5,
        "charging_station" : 0.5,
        "home1"  : 0.5,
        "racheal" : 0.5,
        "monica" : 0.5,
        "left_cupboard" : 0.5,
        "right_cupboard" : 0.5,
        "divya" : 0.5,
        "latika" : 0.5,
        "priyanshu" : 0.5,
        "heena" : 0.5,
        "bishnu" : 0.5,
        "projector" : 0.5
        }

took = {"office_gcn" : False,
        "office_rk" : False,
        "cabin_joey" : False,
        "office_pc" : False,
        "robita_entrance_gate" : False,
        "office_mary" : False,
        "waiting_area" : False,
        "copying_station" : False,
        "cabin_ross" : False,
        "classroom_entrance" : False,
        "robita_lab_entrance" : False,
        "light_switches" : False,
        "classroom_system" :False,
        "whiteboard" : False,
        "wall_ac_front" : False,
        "wall_ac_back" : False,
        "back_right_ac" : False,
        "back_left_ac" :False,
        "charging_station" : False,
        "home1"  : False,
        "racheal" : False,
        "monica" : False,
        "left_cupboard" : False,
        "right_cupboard" : False,
        "divya" : False,
        "latika" : False,
        "priyanshu" : False,
        "heena" : False,
        "bishnu" : False,
        "projector" : False
        }

adj = { "office_gcn" : [27.0,15.2],
        "office_rk" : [27.1,17.4],
        "robita_entrance_gate" : [28.9,16.3],
        "office_mary" : [26.9,18.9],
        "waiting_area" : [29.7,19.2],
        "cabin_joey" : [27.8,24.5],
        "copying_station" : [31.1,24.1],
        "office_pc" : [31.4,26.2],
        "cabin_ross" : [27.8,26.8],
        "classroom_entrance" : [28.4,28],
        "robita_lab_entrance" :[31.7,28.2],
        "light_switches" : [27.4,29.8],
        "classroom_system" :[29.3,32.8],
        "whiteboard" : [29.5,36.7],
        "wall_ac_front" : [28.4,40.9],
        "wall_ac_back" : [23.7,41.0],
        "back_right_ac" : [28.5,34.4],
        "back_left_ac" :[22.5,31.1],
        "charging_station" : [32.9,30.8],
        "home1"  : [33.3,30.8],
        "racheal" : [37.3,30.9],
        "monica" : [40.1,31.2],
        "left_cupboard" : [31.9,32.7],
        "right_cupboard" : [31.8,35.5],
        "divya" : [36.4,37.2],
        "latika" : [39.0,35.6],
        "priyanshu" : [39.4,37.3],
        "heena" : [42.1,32.7],
        "bishnu" : [42.8,36.6],
        "projector" : [28.2,35.3],
        }
order = {"home1" : 0,
        "office_gcn" : 1,
        "office_rk" : 2,
        "cabin_joey" : 6,
        "office_pc" : 8,
        "robita_entrance_gate" : 3,
        "office_mary" : 4,
        "waiting_area" : 5,
        "copying_station" : 7,
        "cabin_ross" : 9,
        "classroom_entrance" : 10,
        "robita_lab_entrance" : 11,
        "light_switches" : 12,
        "classroom_system" :13,
        "whiteboard" : 14,
        "wall_ac_front" : 15,
        "wall_ac_back" : 16,
        "back_right_ac" : 17,
        "back_left_ac" : 18,
        "charging_station" : 19,
        "home2"  : 20,
        "racheal" : 21,
        "monica" : 22,
        "left_cupboard" : 23,
        "right_cupboard" : 24,
        "divya" : 25,
        "latika" : 26,
        "priyanshu" : 27,
        "heena" : 28,
        "bishnu" : 29,
        "projector" : 30
        }